export const genreCategories = [
    {
        id: "popular",
        label: "Populares",
        icon: "✦",
        genres: [
            "rock",
            "pop",
            "jazz",
            "soul",
            "blues",
            "folk",
            "country",
            "metal",
            "punk",
            "reggae",
            "hip hop",
            "electronic",
            "classical",
            "funk",
            "disco",
            "r&b",
            "indie rock",
            "alternative rock",
        ],
    },
    {
        id: "rock",
        label: "Rock y guitarras",
        icon: "🎸",
        genres: [
            "classic rock",
            "hard rock",
            "soft rock",
            "progressive rock",
            "psychedelic rock",
            "garage rock",
            "blues rock",
            "folk rock",
            "southern rock",
            "glam rock",
            "art rock",
            "space rock",
            "post-rock",
            "noise rock",
            "stoner rock",
            "surf rock",
            "indie rock",
            "alternative rock",
            "grunge",
            "britpop",
            "shoegaze",
            "dream pop",
            "new wave",
            "post-punk",
            "gothic rock",
            "emo",
            "pop rock",
            "rock and roll",
        ],
    },
    {
        id: "metal",
        label: "Metal",
        icon: "🤘",
        genres: [
            "heavy metal",
            "thrash metal",
            "death metal",
            "black metal",
            "doom metal",
            "power metal",
            "progressive metal",
            "symphonic metal",
            "folk metal",
            "gothic metal",
            "industrial metal",
            "alternative metal",
            "nu metal",
            "metalcore",
            "deathcore",
            "sludge metal",
            "stoner metal",
            "speed metal",
            "groove metal",
            "post-metal",
        ],
    },
    {
        id: "pop",
        label: "Pop",
        icon: "✨",
        genres: [
            "pop",
            "dance-pop",
            "synth-pop",
            "electropop",
            "indie pop",
            "art pop",
            "chamber pop",
            "dream pop",
            "baroque pop",
            "power pop",
            "teen pop",
            "latin pop",
            "pop soul",
            "pop rock",
            "sunshine pop",
            "ambient pop",
            "experimental pop",
            "adult contemporary",
        ],
    },
    {
        id: "electronic",
        label: "Electrónica",
        icon: "🎛️",
        genres: [
            "electronic",
            "house",
            "deep house",
            "tech house",
            "progressive house",
            "acid house",
            "techno",
            "minimal techno",
            "trance",
            "progressive trance",
            "ambient",
            "downtempo",
            "trip hop",
            "drum and bass",
            "jungle",
            "dubstep",
            "breakbeat",
            "idm",
            "electro",
            "industrial",
            "synthwave",
            "vaporwave",
            "chillwave",
            "future bass",
            "garage",
            "hardcore techno",
            "dance",
        ],
    },
    {
        id: "jazz",
        label: "Jazz y blues",
        icon: "🎷",
        genres: [
            "jazz",
            "bebop",
            "hard bop",
            "cool jazz",
            "free jazz",
            "modal jazz",
            "soul jazz",
            "jazz fusion",
            "smooth jazz",
            "vocal jazz",
            "latin jazz",
            "avant-garde jazz",
            "big band",
            "swing",
            "ragtime",
            "blues",
            "delta blues",
            "chicago blues",
            "electric blues",
            "country blues",
            "jump blues",
            "blues rock",
        ],
    },
    {
        id: "soul",
        label: "Soul, funk y R&B",
        icon: "🕺",
        genres: [
            "soul",
            "neo soul",
            "northern soul",
            "southern soul",
            "blue-eyed soul",
            "psychedelic soul",
            "funk",
            "p-funk",
            "r&b",
            "contemporary r&b",
            "rhythm and blues",
            "motown",
            "disco",
            "boogie",
            "gospel",
            "quiet storm",
        ],
    },
    {
        id: "folk",
        label: "Folk y country",
        icon: "🪕",
        genres: [
            "folk",
            "contemporary folk",
            "indie folk",
            "folk rock",
            "psychedelic folk",
            "traditional folk",
            "americana",
            "country",
            "alt-country",
            "country rock",
            "outlaw country",
            "bluegrass",
            "western swing",
            "honky tonk",
            "singer-songwriter",
            "celtic",
            "celtic folk",
            "appalachian folk",
        ],
    },
    {
        id: "punk",
        label: "Punk y derivados",
        icon: "⚡",
        genres: [
            "punk rock",
            "hardcore punk",
            "post-punk",
            "pop punk",
            "garage punk",
            "crust punk",
            "anarcho-punk",
            "skate punk",
            "street punk",
            "horror punk",
            "noise punk",
            "emo",
            "screamo",
            "post-hardcore",
            "melodic hardcore",
        ],
    },
    {
        id: "urban",
        label: "Hip hop y urbano",
        icon: "🎤",
        genres: [
            "hip hop",
            "rap",
            "alternative hip hop",
            "conscious hip hop",
            "gangsta rap",
            "east coast hip hop",
            "west coast hip hop",
            "southern hip hop",
            "boom bap",
            "jazz rap",
            "experimental hip hop",
            "instrumental hip hop",
            "grime",
            "drill",
            "trap",
            "latin rap",
        ],
    },
    {
        id: "world",
        label: "Músicas del mundo",
        icon: "🌍",
        genres: [
            "world music",
            "afrobeat",
            "highlife",
            "ethio-jazz",
            "rai",
            "arabic music",
            "indian classical",
            "hindustani classical",
            "carnatic",
            "qawwali",
            "flamenco",
            "fado",
            "bossa nova",
            "samba",
            "tango",
            "salsa",
            "merengue",
            "cumbia",
            "bachata",
            "reggaeton",
            "latin",
            "afro-cuban",
            "calypso",
            "soca",
            "klezmer",
            "balkan",
        ],
    },
    {
        id: "reggae",
        label: "Reggae y caribe",
        icon: "🌴",
        genres: [
            "reggae",
            "roots reggae",
            "dub",
            "dancehall",
            "ska",
            "rocksteady",
            "lovers rock",
            "ragga",
            "reggae fusion",
            "calypso",
            "soca",
        ],
    },
    {
        id: "experimental",
        label: "Experimental",
        icon: "🧪",
        genres: [
            "experimental",
            "avant-garde",
            "noise",
            "drone",
            "musique concrète",
            "electroacoustic",
            "minimalism",
            "free improvisation",
            "industrial",
            "dark ambient",
            "plunderphonics",
            "sound collage",
            "lowercase",
        ],
    },
    {
        id: "classical",
        label: "Clásica e instrumental",
        icon: "🎻",
        genres: [
            "classical",
            "baroque",
            "romantic",
            "modern classical",
            "contemporary classical",
            "minimalism",
            "opera",
            "choral",
            "chamber music",
            "symphony",
            "concerto",
            "piano",
            "neoclassical",
            "film score",
            "soundtrack",
            "new age",
            "instrumental",
        ],
    },
];

export const allGenres = Array.from(
    new Set(
        genreCategories.flatMap(
            (category) => category.genres,
        ),
    ),
).sort((first, second) =>
    first.localeCompare(second, "es"),
);