import { useState } from "react";
import { togglePostLike, getPostComments, addPostComment, deletePostComment } from "../services/socialFeed";
import "./SocialPostCard.css";
const reactionLabels = { loved: "Me ha encantado", liked: "Me ha gustado", okay: "Sin más", weak: "Flojo", disliked: "No me ha gustado" };
export default function SocialPostCard({ post, currentUserId, onChanged }) {
    const [liked, setLiked] = useState(Boolean(post.liked_by_me)); const [likeCount, setLikeCount] = useState(Number(post.like_count ?? 0)); const [commentsOpen, setCommentsOpen] = useState(false); const [comments, setComments] = useState([]); const [commentText, setCommentText] = useState(""); const [busy, setBusy] = useState(false);
    async function like() { setBusy(true); try { const next = await togglePostLike({ postId: post.post_id, userId: currentUserId, liked }); setLiked(next); setLikeCount(c => Math.max(0, c + (next ? 1 : -1))); } finally { setBusy(false); } }
    async function openComments() { const next = !commentsOpen; setCommentsOpen(next); if (next && comments.length === 0) setComments(await getPostComments(post.post_id)); }
    async function submit(e) { e.preventDefault(); if (!commentText.trim()) return; setBusy(true); try { await addPostComment({ postId: post.post_id, userId: currentUserId, content: commentText }); setCommentText(""); setComments(await getPostComments(post.post_id)); onChanged?.(); } finally { setBusy(false); } }
    return <article className="social-post"><header className="social-post__header"><div className="social-post__avatar">{post.avatar_url ? <img src={post.avatar_url} alt="" /> : <span>{post.display_name?.charAt(0)?.toUpperCase() ?? "A"}</span>}</div><div><strong>{post.display_name}</strong><span>@{post.username}</span></div><time>{new Date(post.created_at).toLocaleDateString("es-ES", { day: "2-digit", month: "short" })}</time></header><div className="social-post__album"><div className="social-post__cover">{post.cover_url ? <img src={post.cover_url} alt={`Portada de ${post.album_title}`} /> : <span>💿</span>}</div><div><p>HA ESCUCHADO</p><h2>{post.album_title}</h2><h3>{post.artist_name}</h3><div className="social-post__rating"><strong>{Number(post.rating).toFixed(1).replace(".", ",")}</strong><span>{reactionLabels[post.reaction]}</span></div></div></div>{post.review_text && <blockquote>“{post.review_text}”</blockquote>}{post.top_tracks?.length > 0 && <section className="social-post__top"><p>TOP 3 CANCIONES</p><ol>{post.top_tracks.map(t => <li key={t.track_id}><strong>{t.position}</strong><span>{t.title}</span></li>)}</ol></section>}<footer className="social-post__footer"><button type="button" className={liked ? "active" : ""} onClick={like} disabled={busy}>{liked ? "♥" : "♡"} {likeCount}</button><button type="button" onClick={openComments}>💬 {post.comment_count ?? 0}</button>{post.spotify_url && <a href={post.spotify_url} target="_blank" rel="noreferrer">▶ Spotify</a>}</footer>{commentsOpen && <section className="social-comments"><div className="social-comments__list">{comments.map(c => <article key={c.id}><div><strong>{c.profile?.display_name}</strong><p>{c.content}</p></div>{c.user_id === currentUserId && <button type="button" onClick={async () => { await deletePostComment({ commentId: c.id, userId: currentUserId }); setComments(v => v.filter(x => x.id !== c.id)); }}>×</button>}</article>)}</div><form onSubmit={submit}><input value={commentText} onChange={e => setCommentText(e.target.value)} placeholder="Escribe un comentario..." maxLength={1000} /><button type="submit" disabled={busy || !commentText.trim()}>Enviar</button></form></section>}</article>;
}
